version: '3'

services:
        token_info:
                image: cassandra:latest
                ports:
                        - "7000"
                        - "9042"
                volumes:
                        - cassandra_data:/var/lib/cassandra/data
                networks:
                        - cassandra_bridge
                restart: always

                #environment:
                        # - CASSANDRA_SEEDS=cassandra
                        # - CASSANDRA_PASSWORD_SEEDER=yes
                        # - CASSANDRA_PASSWORD=cassandra
        
        microservice_metadata:
                image: cassandra:latest
                ports:
                        - "7000"
                        - "9042"
                volumes:
                        - cassandra_data:/var/lib/cassandra/data
                networks:
                        - monitor_bridge
                restart: always

                #environment:
                        # - CASSANDRA_SEEDS=cassandra
                        # - CASSANDRA_PASSWORD_SEEDER=yes
                        # - CASSANDRA_PASSWORD=cassandra

        permission_matrix:
                image: cassandra:latest
                ports:
                        - "7000"
                        - "9042"
                volumes:
                        - cassandra_data:/var/lib/cassandra/data
                networks:
                        - cassandra_bridge
                restart: always

                #environment:
                        # - CASSANDRA_SEEDS=cassandra
                        # - CASSANDRA_PASSWORD_SEEDER=yes
                        # - CASSANDRA_PASSWORD=cassandra


volumes:
        cassandra_data:
                driver: local

networks:
        cassandra_bridge:
                external: true
        monitor_bridge:
                external: true
