FROM python_basemodel
WORKDIR /container_supervisor
COPY . /container_supervisor
#RUN pip install --no-cache-dir -r requirements.txt --user
ENTRYPOINT ["python3"]
CMD ["system.py"]
#CMD ["sleep","infinity"]
