##### monitor initial tasks list ######

#### "container_type01":[task01,...taskn],"container_type02":[task01,...taskn] ####

init_task = {
        "db_manager":[
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionBitMapperCassandraViewset',
                'name_space':'PermissionPermissionBitMapper.Cassandra_viewset'
                }
            ]
        }

m =    {
        "db_manager":[
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionBitMapperCassandraViewset',
                'name_space':'PermissionPermissionBitMapper.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionBitMapperPostgresqlViewset',
                'name_space':'PermissionPermissionBitMapper.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionBitMapperRedisViewset',
                'name_space':'PermissionPermissionBitMapper.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionCassandraViewset',
                'name_space':'PermissionPermission.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionPostgresqlViewset',
                'name_space':'PermissionPermission.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermission.Redis_viewset',
                'name_space':'PermissionPermission.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupPermissionForItemCassandraViewset',
                'name_space':'PermissionGroupPermissionForItem.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupPermissionForItemPostgresqlViewset',
                'name_space':'PermissionGroupPermissionForItem.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupPermissionForItemRedisViewset',
                'name_space':'PermissionGroupPermissionForItem.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionForModelCassandraViewset',
                'name_space':'PermissionPermissionForModel.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionForModelPostgresqlViewset',
                'name_space':'PermissionPermissionForModel.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionPermissionForModelRedisViewset',
                'name_space':'PermissionPermissionForModel.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupBitsMapperCassandraViewset',
                'name_space':'PermissionGroupBitsMapper.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupBitsMapperPostgresqlViewset',
                'name_space':'PermissionGroupBitsMapper.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupBitsMapperRedisViewset',
                'name_space':'PermissionGroupBitsMapper.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupCassandraViewset',
                'name_space':'PermissionGroup.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupPostgresqlViewset',
                'name_space':'PermissionGroup.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionGroupRedisViewset',
                'name_space':'PermissionGroup.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionUserGroupCassandraViewset',
                'name_space':'PermissionUserGroup.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionUserGroupPostgresqlViewset',
                'name_space':'PermissionUserGroup.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PermissionUserGroupRedisViewset',
                'name_space':'PermissionUserGroup.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ChattingCassandraViewset',
                'name_space':'Chatting.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ChattingPostgresqlViewset',
                'name_space':'Chatting.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ChattingRedisViewset',
                'name_space':'Chatting.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserFollowerCassandraViewset',
                'name_space':'UserFollower.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserFollower.Postgresql_viewset',
                'name_space':'UserFollower.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserFollowerRedisViewset',
                'name_space':'UserFollower.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserIsAFollowerCassandraViewset',
                'name_space':'UserIsAFollower.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserIsAFollowerPostgresqlViewset',
                'name_space':'UserIsAFollower.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserIsAFollowerRedisViewset',
                'name_space':'UserIsAFollower.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'NotificationCassandraViewset',
                'name_space':'Notification.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'NotificationPostgresqlViewset',
                'name_space':'Notification.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'NotificationRedisViewset',
                'name_space':'Notification.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostCommentCassandraViewset',
                'name_space':'PostComment.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostComment.PostgresqlViewset',
                'name_space':'PostComment.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostCommentRedisViewset',
                'name_space':'PostComment.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'LikePostCassandraViewset',
                'name_space':'LikePost.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'LikePostPostgresqlViewset',
                'name_space':'LikePost.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'LikePostRedisViewset',
                'name_space':'LikePost.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostLikedByUserCassandraViewset',
                'name_space':'PostLikedByUser.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostLikedByUserPostgresqlViewset',
                'name_space':'PostLikedByUser.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostLikedByUserRedisViewset',
                'name_space':'PostLikedByUser.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'SavePostCassandraViewset',
                'name_space':'SavePost.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'SavePostPostgresqlViewset',
                'name_space':'SavePost.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'SavePostRedisViewset',
                'name_space':'SavePost.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostCassandraViewset',
                'name_space':'Post.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostPostgresqlViewset',
                'name_space':'Post.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostRedisViewset',
                'name_space':'Post.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserPostCassandraViewset',
                'name_space':'UserPost.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserPostPostgresqlViewset',
                'name_space':'UserPost.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserPostRedisViewset',
                'name_space':'UserPost.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostForUserCassandraViewset',
                'name_space':'PostForUser.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostForUserPostgresqlViewset',
                'name_space':'PostForUser.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostForUserRedisViewset',
                'name_space':'PostForUser.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserViewCassandraViewset',
                'name_space':'UserView.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserViewPostgresqlViewset',
                'name_space':'UserView.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'UserViewRedisViewset',
                'name_space':'UserView.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostViewCassandraViewset',
                'name_space':'PostView.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostViewPostgresqlViewset',
                'name_space':'PostView.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PostViewRedisViewset',
                'name_space':'PostView.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'CustomUserCassandraViewset',
                'name_space':'CustomUser.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'CustomUserPostgresqlViewset',
                'name_space':'CustomUser.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'CustomUserRedisViewset',
                'name_space':'CustomUser.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ProfileCassandraViewset',
                'name_space':'Profile.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ProfilePostgresqlViewset',
                'name_space':'Profile.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ProfileRedisViewset',
                'name_space':'Profile.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ItemStatusCassandraViewset',
                'name_space':'ItemStatus.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ItemStatusPostgresqlViewset',
                'name_space':'ItemStatus.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'ItemStatusRedisViewset',
                'name_space':'ItemStatus.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PersonalCassandraViewset',
                'name_space':'Personal.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PersonalPostgresqlViewset',
                'name_space':'Personal.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'PersonalRedisViewset',
                'name_space':'Personal.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'VideoCassandraViewset',
                'name_space':'Video.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'VideoPostgresqlViewset',
                'name_space':'Video.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'VideoRedisViewset',
                'name_space':'Video.Redis_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'WatchTogetherCassandraViewset',
                'name_space':'WatchTogether.Cassandra_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'WatchTogetherPostgresqlViewset',
                'name_space':'WatchTogether.Postgresql_viewset'
                },
            {
                "service_models":"UI",
                "class_name":'WatchTogetherRedisViewset',
                'name_space':'WatchTogether.Redis_viewset'
                }

            ],### manager_container
        "ui":[
            {
                "service_models":"UI",
                "class_name":'LikeViewSet',
                'name_space':'likes_api.like_api_viewset'
                },
            {
                "service_models":"UI",
                "class_name":"PostViewset",
                "name_space":"posts_api.post_viewset"
            },
            {   
                "service_models":"UI",
                "class_name":"SaveViewset",
                "name_space":"saves_api.save_api_viewset"
            },
            {   
                "service_models":"UI",
                "class_name":"ShareViewSet",
                "name_space":"shares_api.share_api_viewset"
            },
            {   
                "service_models":"UI",   
                "class_name":"StoryViewset",
                "name_space":"stories_api.stories_viewset"
            },
            {   
                "service_models":"UI",
                "class_name":"ViewViewset",
                "name_space":"views_api.views_viewset"
            },
            {   
                "service_models":"UI",
                "class_name":"CommentViewset",
                "name_space":"comments_api.comments_viewset"
            },
            {
                "service_models":"UI",
                "class_name":"FollowerViewset",
                "name_space":"followers_api.follower_viewset"
            }
            ]### ui_container
        }

